const teams={CSK:'Chennai Super Kings',DC:'Delhi Capitals',GT:'Gujarat Titans',KKR:'Kolkata Knight Riders',LSG:'Lucknow Super Giants',MI:'Mumbai Indians',PBKS:'Punjab Kings',RR:'Rajasthan Royals',RCB:'Royal Challengers Bengaluru',SRH:'Sunrisers Hyderabad'};
const profiles={CSK:.86,DC:.92,GT:.87,KKR:.78,LSG:.94,MI:.82,PBKS:.76,RR:.96,RCB:.79,SRH:.88};
const sets=[
{name:'Marquee Players',p:[['Virat Kohli','India','BAT',37,2,95,97,20,91],['Jasprit Bumrah','India','BOWL',32,2,96,25,98,88],['Suryakumar Yadav','India','BAT',35,2,94,97,24,90],['Rashid Khan','Afghanistan','AR',27,2,94,63,97,92],['Shubman Gill','India','BAT',27,2,93,96,18,88],['Heinrich Klaasen','South Africa','WK',35,2,93,96,5,87]]},
{name:'Top Batters',p:[['Yashasvi Jaiswal','India','BAT',24,1.5,92,95,15,84],['Ruturaj Gaikwad','India','BAT',29,1.5,90,94,18,85],['Rinku Singh','India','BAT',28,1,85,89,10,84],['Tilak Varma','India','BAT',23,1,86,91,32,86],['Rajat Patidar','India','BAT',33,1,84,87,12,82],['Travis Head','Australia','BAT',32,2,92,96,25,86],['David Miller','South Africa','BAT',37,1.5,85,88,10,86],['Phil Salt','England','WK',30,1.5,87,91,8,82]]},
{name:'All-Rounders',p:[['Ravindra Jadeja','India','AR',37,2,92,85,89,96],['Hardik Pandya','India','AR',33,2,91,88,82,86],['Axar Patel','India','AR',32,2,89,79,88,91],['Abhishek Sharma','India','AR',26,1,87,91,61,83],['Shivam Dube','India','AR',33,1,84,87,58,76],['Liam Livingstone','England','AR',33,1.5,88,90,76,82],['Sunil Narine','West Indies','AR',38,1.5,90,81,94,90],['Marco Jansen','South Africa','AR',26,1,85,73,89,84]]},
{name:'Fast & Spin Bowlers',p:[['Arshdeep Singh','India','BOWL',27,2,88,25,92,82],['Mohammed Siraj','India','BOWL',32,2,87,24,90,78],['Kuldeep Yadav','India','BOWL',31,2,87,30,91,79],['Varun Chakravarthy','India','BOWL',35,2,88,22,91,80],['Yuzvendra Chahal','India','BOWL',36,1.5,86,20,89,75],['Matheesha Pathirana','Sri Lanka','BOWL',23,1.5,89,35,94,78],['Pat Cummins','Australia','BOWL',33,2,91,62,93,86],['Josh Hazlewood','Australia','BOWL',35,2,91,18,95,85],['Adam Zampa','Australia','BOWL',34,1.5,85,20,90,80],['Mitchell Starc','Australia','BOWL',36,2,89,48,94,82]]},
{name:'Wicketkeepers',p:[['Rishabh Pant','India','WK',29,2,93,94,10,92],['KL Rahul','India','WK',34,2,90,92,12,89],['Sanju Samson','India','WK',31,1.5,90,93,10,91],['Ishan Kishan','India','WK',28,1.5,86,88,8,85],['Jitesh Sharma','India','WK',33,1,82,85,8,82],['Nicholas Pooran','West Indies','WK',30,2,91,94,8,86],['Jos Buttler','England','WK',35,2,92,95,8,89]]},
{name:'Emerging & Uncapped',p:[['Prashant Veer','India','AR',23,.3,76,78,70,78],['Kartik Sharma','India','WK',21,.3,75,79,8,76],['Vaibhav Suryavanshi','India','BAT',15,.3,74,80,8,72],['Prabhsimran Singh','India','WK',25,.5,78,81,8,78],['Nitish Kumar Reddy','India','AR',23,1,84,84,68,84],['Devdutt Padikkal','India','BAT',26,1,79,82,10,79],['Jake Fraser-McGurk','Australia','BAT',24,1,83,89,8,80]]}
];
const A={};let state={team:'CSK',set:0,idx:0,current:null,bid:0,bidder:null,running:false,seconds:12,timer:null,started:false};
for(const c in teams)A[c]={purse:120,squad:[]};
const $=x=>document.getElementById(x),money=x=>'₹'+Number(x).toFixed(2)+' Cr',role=r=>({BAT:'BATTER',BOWL:'BOWLER',AR:'ALL-ROUNDER',WK:'WICKETKEEPER'}[r]);
function make(raw){return{id:Math.random(),name:raw[0],country:raw[1],role:raw[2],age:raw[3],base:raw[4],overall:raw[5],bat:raw[6],bowl:raw[7],field:raw[8],os:raw[1]!=='India'}}
function inc(v){return v<3?.2:v<5?.25:v<10?.5:v<15?1:2}
function fair(c,p){let s=A[c].squad,need=0;if(p.role==='BOWL'&&s.filter(x=>x.role==='BOWL').length<3)need+=1.5;if(p.role==='BAT'&&s.filter(x=>x.role==='BAT').length<3)need+=1.2;if(p.role==='AR'&&s.filter(x=>x.role==='AR').length<2)need+=1.5;if(p.role==='WK'&&s.filter(x=>x.role==='WK').length<2)need+=1.3;let v=p.base+(p.overall-70)*.055+need;if(p.overall>=90)v+=.5;if(p.age<=25)v+=.35;v*=profiles[c];return Math.max(p.base,+v.toFixed(2))}
function can(c,p,price){let t=A[c];return t.purse>=price&&t.squad.length<25&&(!p.os||t.squad.filter(x=>x.os).length<8)}
function next(){let arr=sets[state.set].p.map(make);state.pool=arr;if(state.idx>=arr.length){finishSet();return}state.current=arr[state.idx];state.bid=state.current.base;state.bidder=null;state.running=true;state.seconds=12;render();startClock();setTimeout(ai,700)}
function startClock(){clearInterval(state.timer);state.timer=setInterval(()=>{if(!state.running)return;state.seconds--;renderTimer();if(state.seconds<=0){clearInterval(state.timer);sell()}},1000)}
function resetClock(){state.seconds=12;renderTimer();startClock()}
function ai(){if(!state.running||!state.current)return;let p=state.current,price=+(state.bid+inc(state.bid)).toFixed(2),candidates=Object.keys(teams).filter(c=>c!==state.team&&can(c,p,price)&&price<=fair(c,p)+.35);if(candidates.length&&Math.random()<.72){candidates.sort((a,b)=>fair(b,p)-fair(a,p));let c=candidates[Math.floor(Math.random()*Math.min(3,candidates.length))];state.bid=price;state.bidder=c;log(`${teams[c]} bids ${money(price)} for ${p.name}.`);render();resetClock();setTimeout(ai,650+Math.random()*800)}else if(state.bidder===null&&Math.random()<.35){let cheap=Object.keys(teams).filter(c=>c!==state.team&&can(c,p,price)&&price<=fair(c,p));if(cheap.length){let c=cheap[Math.floor(Math.random()*cheap.length)];state.bid=price;state.bidder=c;log(`${teams[c]} opens at ${money(price)}.`);render();resetClock();setTimeout(ai,700)}}}
function userBid(){if(!state.running)return;let price=+(state.bid+inc(state.bid)).toFixed(2);if(!can(state.team,state.current,price)){state.status='You cannot afford that bid or a squad limit blocks it.';render();return}state.bid=price;state.bidder=state.team;log(`YOU bid ${money(price)} for ${state.current.name}.`,'good');render();resetClock();setTimeout(ai,700)}
function pass(){if(!state.running)return;log(`You passed on ${state.current.name}.`);sell()}
function sell(){if(!state.running||!state.current)return;state.running=false;clearInterval(state.timer);let p=state.current;if(state.bidder){A[state.bidder].purse=+(A[state.bidder].purse-state.bid).toFixed(2);A[state.bidder].squad.push({...p,price:state.bid});log(`SOLD — ${p.name} to ${teams[state.bidder]} for ${money(state.bid)}.`,'good');if(state.bidder===state.team)state.status=`You bought ${p.name} for ${money(state.bid)}.`}else log(`UNSOLD — ${p.name}.`,'bad');render();setTimeout(()=>{state.idx++;next()},1100)}
function start(){clearInterval(state.timer);for(const c in A){A[c].purse=120;A[c].squad=[]}state.team=$('team').value;state.set=state.selectedSet??0;state.idx=0;state.started=true;$('feed').innerHTML='';log(`Auction started — ${teams[state.team]}`);log(`Set: ${sets[state.set].name}`);next()}
function selectSet(i){if(state.started&&state.running){toast('Finish the current player first.');return}state.selectedSet=i;state.set=i;renderSets();render();}
function finishSet(){state.started=false;state.running=false;clearInterval(state.timer);let t=A[state.team],spent=120-t.purse;$('reportTitle').textContent=sets[state.set].name;$('report').innerHTML=`<div class="reportstats"><div><small>PLAYERS BOUGHT</small><b>${t.squad.length}</b></div><div><small>SPENT</small><b>${money(spent)}</b></div><div><small>REMAINING</small><b>${money(t.purse)}</b></div></div><div style="margin-top:15px">${t.squad.map(p=>`<div class="reportline"><span>${p.name} • ${role(p.role)}</span><b class="gold">${money(p.price)}</b></div>`).join('')||'<p>No purchases in this set.</p>'}</div>`;$('modal').classList.remove('hidden');render()}
function log(text,cl=''){let d=document.createElement('div');d.className='event '+cl;d.innerHTML=`<span class="time">${new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'})}</span><b>${text}</b>`;$('feed').prepend(d)}
function renderTimer(){$('timer').textContent=state.running?state.seconds:'—'}
function renderSets(){$('sets').innerHTML=sets.map((s,i)=>`<div class="set ${i===state.set?'active':''} ${state.started&&i!==state.set?'locked':''}" onclick="selectSet(${i})"><span>${i+1}. ${s.name}</span><span>${s.p.length}</span></div>`).join('');$('setNo').textContent=`${state.set+1}/6`;$('setName').textContent=sets[state.set].name}
function renderPlayer(){let p=state.current;if(!p){$('name').textContent=state.started?'Set Complete':'Ready for Auction';$('details').textContent=state.started?'':'Choose your franchise and click NEW AUCTION.';return}let ini=p.name.split(' ').map(x=>x[0]).slice(0,2).join('');$('avatar').textContent=ini;$('role').textContent=role(p.role);$('nation').textContent=p.os?'OVERSEAS':'INDIAN';$('name').textContent=p.name;$('details').textContent=`${p.country} • ${p.age} years • ${role(p.role)}`;$('ovr').textContent=p.overall;$('bat').textContent=p.bat;$('bowl').textContent=p.bowl;$('field').textContent=p.field;$('batbar').style.width=p.bat+'%';$('bowlbar').style.width=p.bowl+'%';$('fieldbar').style.width=p.field+'%';$('base').textContent=money(p.base);$('current').textContent=money(state.bid);$('bidder').textContent=state.bidder?teams[state.bidder]:'Opening price';$('next').textContent=money(state.bid+inc(state.bid));$('bid').disabled=!state.running;$('pass').disabled=!state.running;$('status').textContent=state.status||'Bid before the timer reaches zero. AI teams will compete for valuable players.'}
function render(){renderSets();renderPlayer();renderTimer();let t=A[state.team];$('purse').textContent=money(t.purse);$('count').textContent=`${t.squad.length}/25`;$('os').textContent=`${t.squad.filter(x=>x.os).length}/8`;$('purseBar').style.width=(t.purse/120*100)+'%';let roles={BAT:0,BOWL:0,AR:0,WK:0};t.squad.forEach(p=>roles[p.role]++);$('roleCount').textContent=`${roles.BAT}B / ${roles.BOWL}W / ${roles.AR}AR / ${roles.WK}WK`;$('squad').innerHTML=t.squad.length?t.squad.map(p=>`<div class="squadline"><span><b>${p.name}</b><small>${role(p.role)} • ${p.os?'OS':'IND'}</small></span><b class="gold">${money(p.price)}</b></div>`).join(''):'<div class="empty">No players yet.</div>';$('teams').innerHTML=Object.keys(teams).map(c=>`<div class="teamline ${c===state.team?'you':''}"><div class="code">${c}</div><div class="tn">${teams[c]}${c===state.team?' • YOU':''}</div><div class="cash">${money(A[c].purse)}</div></div>`).join('');let rest=state.pool?state.pool.slice(state.idx+1):sets[state.set].p.map(make);$('upcoming').innerHTML=rest.slice(0,7).map(p=>`<div class="up"><span><b>${p.name}</b><small>${role(p.role)} • ${p.os?'OS':'IND'}</small></span><b class="gold">${money(p.base)}</b></div>`).join('')}
function toast(m){let x=document.createElement('div');x.textContent=m;x.style='position:fixed;bottom:25px;left:50%;transform:translateX(-50%);background:#1a2233;border:1px solid #33405a;padding:11px 15px;border-radius:9px;z-index:30';document.body.appendChild(x);setTimeout(()=>x.remove(),1500)}
Object.entries(teams).forEach(([c,n])=>$('team').insertAdjacentHTML('beforeend',`<option value="${c}">${n}</option>`));$('team').value='CSK';$('newBtn').onclick=start;$('bid').onclick=userBid;$('pass').onclick=pass;$('clear').onclick=()=>$('feed').innerHTML='';$('close').onclick=()=>$('modal').classList.add('hidden');render();
