const TEAM_NAMES={CSK:"Chennai Super Kings",DC:"Delhi Capitals",GT:"Gujarat Titans",KKR:"Kolkata Knight Riders",LSG:"Lucknow Super Giants",MI:"Mumbai Indians",PBKS:"Punjab Kings",RR:"Rajasthan Royals",RCB:"Royal Challengers Bengaluru",SRH:"Sunrisers Hyderabad"};
const AI_PROFILES={CSK:{ag:.42,val:.80,star:.65},DC:{ag:.36,val:.95,star:.55},GT:{ag:.43,val:.85,star:.62},KKR:{ag:.58,val:.68,star:.72},LSG:{ag:.38,val:1,star:.60},MI:{ag:.54,val:.72,star:.85},PBKS:{ag:.50,val:.62,star:.78},RR:{ag:.34,val:1,star:.58},RCB:{ag:.56,val:.64,star:.90},SRH:{ag:.46,val:.82,star:.75}};
class AuctionEngine{
constructor(){this.teams={};Object.keys(TEAM_NAMES).forEach(c=>this.teams[c]={code:c,name:TEAM_NAMES[c],purse:120,squad:[]});this.userTeam="CSK";this.setIndex=0;this.queue=[];this.lotIndex=-1;this.currentPlayer=null;this.currentBid=0;this.currentBidder=null;this.finished=false}
start(team,set){this.userTeam=team;this.setIndex=set;this.queue=[...AUCTION_SETS[set].players];this.lotIndex=-1;this.finished=false;this.nextPlayer()}
nextPlayer(){this.lotIndex++;if(this.lotIndex>=this.queue.length){this.finished=true;this.currentPlayer=null;return null}this.currentPlayer=this.queue[this.lotIndex];this.currentBid=this.currentPlayer.base;this.currentBidder=null;return this.currentPlayer}
increment(p){if(p<3)return .2;if(p<5)return .25;if(p<10)return .5;if(p<15)return 1;return 2}
nextBid(){return +(this.currentBid+this.increment(this.currentBid)).toFixed(2)}
canBuy(c,p,price){let t=this.teams[c];return !!t&&t.purse>=price&&t.squad.length<25&&(p.nation==="IND"||t.squad.filter(x=>x.nation==="OS").length<8)}
need(c,p){let s=this.teams[c].squad,n=s.filter(x=>x.role===p.role).length,score=s.length<7?10:0;if(p.role==="BAT"&&n<3)score+=10;if(p.role==="BOWL"&&n<4)score+=14;if(p.role==="AR"&&n<2)score+=18;if(p.role==="WK"&&n<2)score+=14;if(p.nation==="OS"&&s.filter(x=>x.nation==="OS").length<3)score+=5;return score}
fair(c,p){let q=AI_PROFILES[c],v=p.base+(p.overall-70)*.055+this.need(c,p)*.025;v*=q.val;if(p.overall>=90)v+=q.star*.8;if(p.age<=25)v+=.25;if(p.role==="AR")v+=.25;return Math.max(p.base,+v.toFixed(2))}
aiBid(){if(!this.currentPlayer)return{type:"none"};let price=this.nextBid(),eligible=Object.keys(this.teams).filter(c=>c!==this.userTeam).filter(c=>this.canBuy(c,this.currentPlayer,price)).filter(c=>price<=this.fair(c,this.currentPlayer)+AI_PROFILES[c].ag+(Math.random()-.5)*.8);if(!eligible.length)return{type:"none"};eligible.sort((a,b)=>this.fair(b,this.currentPlayer)-this.fair(a,this.currentPlayer));let c=eligible[Math.floor(Math.random()*Math.min(3,eligible.length))];this.currentBid=price;this.currentBidder=c;return{type:"ai_bid",team:c,price}}
userBid(){let p=this.nextBid();if(!this.currentPlayer)return{type:"invalid"};if(!this.canBuy(this.userTeam,this.currentPlayer,p))return{type:"cannot",reason:"You cannot afford this bid or a squad limit prevents it."};this.currentBid=p;this.currentBidder=this.userTeam;return{type:"user_bid",price:p}}
sell(){if(!this.currentPlayer)return{type:"none"};if(!this.currentBidder)return{type:"unsold",player:this.currentPlayer};let t=this.teams[this.currentBidder],p=this.currentPlayer;t.purse=+(t.purse-this.currentBid).toFixed(2);t.squad.push({...p,soldPrice:this.currentBid});return{type:"sold",player:p,team:this.currentBidder,price:this.currentBid}}
getUser(){return this.teams[this.userTeam]}remaining(){return this.queue.slice(this.lotIndex+1)}
}
